server:
  port: 8082

spring:
  application:
    name: mall-demo
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false #开发时关闭缓存,不然没法看到实时页面
  # rabbitmq配置
  rabbitmq:
    host: 39.105.6.8
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    #支持发布确认，已被废弃
    #publisher-confirms: true
    #确认消息已经发送到交换机（exchange）选择确认类型为交互
    publisher-confirm-type: correlated
    #支持发布返回
    publisher-returns: true
    #采用手动应答
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 3
        retry:
          enabled: true
          max-attempts: 3
          max-interval: 20000   # 重试最大间隔时间
          initial-interval: 2000  # 重试初始间隔时间
          multiplier: 3 # 间隔时间乘子，间隔时间*乘子=下一次的间隔时间，最大不能超过设置的最大间隔时间
      direct:
        acknowledge-mode: manual

  redis:
    host: 39.105.6.8 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

logging:
  level:
    root: info
    com.macro.mall: debug

host:
  mall:
   admin: http://localhost:8080
