server:
  port: 8082

spring:
  application:
    name: mall-demo
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false #开发时关闭缓存,不然没法看到实时页面
  # rabbitmq配置
  rabbitmq:
    host: 39.105.6.8
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    #支持发布确认，已被废弃
    #publisher-confirms: true
    #确认消息已经发送到交换机（exchange）选择确认类型为交互
    publisher-confirm-type: correlated
    #支持发布返回
    publisher-returns: true
    #采用手动应答
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 3
        retry:
          enabled: true
      direct:
        acknowledge-mode: manual


mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

logging:
  level:
    root: info
    com.macro.mall: debug

host:
  mall:
   admin: http://localhost:8080
