server:
  port: 8082

spring:
  application:
    name: mall-mq
  datasource:
    url: jdbc:mysql://30.105.6.8:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: wnGZy2rww
  ## QQ邮箱配置
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 610813893@qq.com #发送邮件的邮箱地址
    password:  raozmnsyufwebbah #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 610813893@qq.com # 发送邮件的地址，和上面username一致可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

logging:
  level:
    root: info
    com.macro.mall: debug
