server:
  port: 8082

spring:
  application:
    name: mall-mq
  datasource:
    url: jdbc:mysql://30.105.6.8:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: wnGZy2rww
  # rabbitmq配置
  rabbitmq:
    host: 39.105.6.8
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    #支持发布确认，已被废弃
    #publisher-confirms: true
    #确认消息已经发送到交换机（exchange）选择确认类型为交互
    publisher-confirm-type: correlated
    #支持发布返回
    publisher-returns: true
    #采用手动应答
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 3
        retry:
          enabled: true
      direct:
        acknowledge-mode: manual
  redis:
    host: 30.105.6.8 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    password: abc
    username: 610813893@qq.com
    port: 587
    properties:
      mail:
        debug: true
        stmp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

logging:
  level:
    root: info
    com.macro.mall: debug
